"use client";

// Ambient world-map backdrop for the user dashboard (desktop only).
//
// A faint line-art world map drifts almost imperceptibly behind the content —
// passive geography familiarity with zero interaction cost. Guarantees:
//   · never intercepts input (pointer-events: none, fixed, negative z),
//   · never harms legibility (hairline strokes ≤0.09 opacity, radially masked),
//   · costs nothing at runtime (single SVG, transform-only CSS animation),
//   · invisible on <lg (mobile GPUs/battery spared) and under reduced motion,
//   · hidden in forced-colors mode (decorative vectors smear there).
// Asset: frontend/lib/data/world-map.ts (generated by scripts/build-world-map.ts).

import { useEffect, useState } from "react";
import { WORLD_MAP_PATH, WORLD_MAP_VIEWBOX, DHAKA_SPOT } from "@/lib/data/world-map";
import { api } from "@/lib/services/api";
import { useEcosystem } from "@/lib/ecosystem-ctx";

type Hotspot = { x: number; y: number; label: string };

// Geography-flavoured weak topics map to regional hotspots (viewBox coords
// of frontend/lib/data/world-map.ts, 1000×500 equirectangular).
const REGION_SPOTS: { match: RegExp; spot: { x: number; y: number }; label: string }[] = [
  { match: /বাংলাদেশ|bangladesh/i, spot: DHAKA_SPOT, label: "Bangladesh" },
  // South Asia neighbourhood.
  { match: /ভারত|india|পাকিস্তান|pakistan|নেপাল|nepal|ভুটান|bhutan|দক্ষিণ এশিয়া|south asia/i, spot: { x: 716, y: 195 }, label: "South Asia" },
  // Middle East / Central Asia.
  { match: /মধ্যপ্রাচ্য|middle east|মধ্য এশিয়া|central asia|আরব|arab/i, spot: { x: 622, y: 182 }, label: "Middle East" },
  // Europe.
  { match: /ইউরোপ|europe/i, spot: { x: 528, y: 118 }, label: "Europe" },
  // Africa.
  { match: /আফ্রিকা|africa/i, spot: { x: 555, y: 240 }, label: "Africa" },
  // East / Southeast Asia.
  { match: /চীন|china|জাপান|japan|পূর্ব এশিয়া|east asia|দক্ষিণ-পূর্ব|দক্ষিণপূর্ব|southeast/i, spot: { x: 815, y: 160 }, label: "East Asia" },
  // North America.
  { match: /আমেরিকা|america|যুক্তরাষ্ট্র|usa/i, spot: { x: 222, y: 130 }, label: "North America" },
  // Oceans / environment (Indian Ocean).
  { match: /মহাসাগর|ocean|সাগর|sea|পরিবেশ|environment|জলবায়ু|climate/i, spot: { x: 722, y: 333 }, label: "Oceans" },
];

function spotForWeakTopic(weakTopic: string | null): Hotspot {
  if (weakTopic) {
    for (const r of REGION_SPOTS) {
      if (r.match.test(weakTopic)) return { ...r.spot, label: r.label };
    }
  }
  return { ...DHAKA_SPOT, label: "Bangladesh" };
}

export default function WorldMapBackdrop() {
  const { ecosystem } = useEcosystem();
  const [hotspot, setHotspot] = useState<Hotspot>({ ...DHAKA_SPOT, label: "Bangladesh" });

  // Bind the pulse to the learner's weakest geography-flavoured topic.
  // Non-fatal: any failure keeps the default Dhaka spotlight.
  useEffect(() => {
    let cancelled = false;
    void api
      .preparationIntelligence()
      .then((intel) => {
        if (cancelled) return;
        const weak = intel?.weakTopics?.[0] as unknown as { topic?: string } | undefined;
        setHotspot(spotForWeakTopic(weak?.topic ?? null));
      })
      .catch(() => {
        // keep default
      });
    return () => {
      cancelled = true;
    };
  }, [ecosystem]);

  return (
    <div
      aria-hidden="true"
      className="world-map-backdrop pointer-events-none fixed inset-0 hidden overflow-hidden lg:block"
    >
      <div className="world-map-drift absolute">
        <svg
          viewBox={WORLD_MAP_VIEWBOX}
          className="world-map-svg"
          focusable="false"
        >
          <path d={WORLD_MAP_PATH} className="world-map-land" />
        </svg>
        {/* Weak-topic spotlight — one pulsing dot, position in % of viewBox */}
        <span
          className="world-map-spot"
          style={{
            left: `${(hotspot.x / 1000) * 100}%`,
            top: `${(hotspot.y / 500) * 100}%`,
          }}
        >
          <span className="world-map-spot-ring" />
          <span className="world-map-spot-dot" />
          <span className="world-map-spot-label">{hotspot.label}</span>
        </span>
      </div>
    </div>
  );
}
